name: fanli 
on:
  schedule:
    - cron: '35 */12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-fanli
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
#       - name: sync fanli_jd
#         uses: repo-sync/github-sync@v2
#         with:
#           source_repo: "https://github.com/hdbjlizhe/fanli_jd.git"
#           source_branch: "main"
#           destination_branch: "fanli_jd"
#           github_token: ${{ secrets.PAT }}
#       - name: sync fanli_tb
#         uses: repo-sync/github-sync@v2
#         if: env.PAT          
#         with:
#           source_repo: "https://github.com/hdbjlizhe/fanli_tb.git"
#           source_branch: "main"
#           destination_branch: "fanli_tb"
#           github_token: ${{ secrets.PAT }}
#       - name: sync fanli_pdd
#         uses: repo-sync/github-sync@v2
#         if: env.PAT
#         with:
#           source_repo: "https://github.com/hdbjlizhe/fanli_pdd.git"
#           source_branch: "main"
#           destination_branch: "fanli_pdd"    
#           github_token: ${{ secrets.PAT }}
#       - name: sync Ark
#         uses: repo-sync/github-sync@v2
#         if: env.PAT
#         with:
#           source_repo: "https://github.com/NNNNolan/Ark.git"
#           source_branch: "main"
#           destination_branch: "Ark"    
#           github_token: ${{ secrets.PAT }}
      - name: sync fake2
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/shufflewzc/faker2.git"
          source_branch: "main"
          destination_branch: "faker2"    
          github_token: ${{ secrets.PAT }}
