name: jd_cookie-sync 
on:
  schedule:
    - cron: '35 */12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-jd_cookie-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync jd_cookie-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ufuckee/jd_cookie.git"
          source_branch: "master"
          destination_branch: "jd_cookie"
          github_token: ${{ secrets.PAT }}
