name: JD_Diy-sync 
on:
  schedule:
    - cron: '50 */8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: JD_Diy-sync-x
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync JD_Diy
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/chiupam/JD_Diy.git"
          source_branch: "master"
          destination_branch: "JD_Diy"
          github_token: ${{ secrets.PAT }}
